name: app-build-release-action
# 手动触发
on:
  workflow_dispatch:

jobs:
  # 打包MacOS
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      # 设置JAVA环境
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      # Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          cache: true

      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop

      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Install appdmg
        run: npm install -g appdmg

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build MacOS
        run: |
          cd simple_live_app
          flutter_distributor package --platform macos --targets dmg,zip --skip-clean

      - uses: actions/upload-artifact@v4
        with:
          name: mac
          path: |
            simple_live_app/build/dist/*/*.dmg
            simple_live_app/build/dist/*/*.zip

  # 打包Windows
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.x"
          cache: true

      - run: flutter config --enable-windows-desktop

      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get

      - run: dart pub global activate flutter_distributor

      - name: Build Windows
        run: |
          cd simple_live_app
          flutter_distributor package --platform windows --targets msix,zip --skip-clean

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            simple_live_app/build/dist/*/*.msix
            simple_live_app/build/dist/*/*.zip
